### ISSUE TITLE
[dx] - devtools plugin

### ISSUE THREAD

**Issue by JonasBa** [algolia/search-insights.js#10]
Consider adding a devtools plugin similar to the one of Google Analytics, that would show the events that are successfully sent. Maybe add an integration to the algolia devtools plugin that @R4ph-t is working on?

Events to show:
- click
- conversion

Data to surface:
- successfull event?
- filters used
- query

**Comment by tkrugg** [comment]
This was achieved: https://www.algolia.com/doc/guides/getting-insights-and-analytics/search-analytics/click-through-and-conversions/in-depth/insights-validator-plugin/
