### ISSUE TITLE
Respect User Tracking preferences - navigator.doNotTrack

### ISSUE THREAD

**Issue by JonasBa** [algolia/search-insights.js#110]
Today none of our tracking libraries respect the `Navigator.doNotTrack`, we should use this property to either educate developers and our users about it's usage or make sure that our own libraries respect the spec by not tracking users who explicitly prefer not to be tracked.

**Disclaimer:**
_Spec status is currently Candidate Recommendation, tho the feature seems to have been very quickly adopted by most browsers ([see compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack#Browser_compatibility))_

Considering the implementation, I see a few ways we could approach it:

- disable sending of XHR/sendbeacon requests in search-insights.js
  - Pros: enforced
  - Cons: searches are still tracked and the library is hiding an important part of the implementation + we'd have no way to monitor the frequency of this

- Overriding clickAnalytics=true at query time inside the helper/core so that those searches 
  - Pros: searches are not tracked (smaller product impact)
  - Cons: library is again hiding an important part of the implementation + no monitoring

-  Documenting and educations developers decide on how to handle this
   - Pros: Educates users/developers, clear part of the documentation that also shows our users we care about this
   - Cons: Not reliable and can easily be neglected by lack of care

First approach has a negative product implication in terms of CTR and Conversion metrics, which are today linked to number of tracked searches. If a search is not tracked however, the relative % of CTR and Conversion will not change, thus making the second approach a bit more favourable.

I imagine this could also be a very wide debate, solvable in many different ways.

**Spec and documents:**
[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack) 
[See proposal spec](https://w3c.github.io/dnt/drafts/tracking-dnt.html#js-dom)

**Comment by Haroenv** [comment]
Is there a reason you don't suggest doing _both_ 1 & 2?

**Comment by JonasBa** [comment]
If we do 2, then 1 is not needed because you won't generate a queryID anyways, so even tho data will be sent to us, it will be useless because we can't coordinate it with any queryID

**Comment by Haroenv** [comment]
In that case, I guess it can be done backend too, since DNT is a header which is sent; and in that case we can not return a query id

**Comment by benhinchley** [comment]
`Navigator.doNotTrack` is now deprecated and is no longer recommended.
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack
