### ISSUE TITLE
startsWith causes error in IE10

### ISSUE THREAD

**Issue by emuvente** [algolia/search-insights.js#122]
Console error in Internet Explorer 10, Windows 7, visiting https://www.kiva.org/algolia-vue
`Object doesn't support property or method 'startsWith'  search-insights@1.0.0, line 1 character 13668`

The code at that position:
`...t&&""!==t&&t.startsWith("anonymous-")?this._userTok...`

**Comment by Haroenv** [comment]
Looks indeed like this needs a polyfill: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

**Comment by tkrugg** [comment]
this was fixed in #129
