### ISSUE TITLE
# tests(cts): update send_event/send_events tests adding timestamp

### ISSUE THREAD

**Issue by nunomaduro** [algolia/search-insights.js#126]
**Docs**: https://github.com/algolia/algoliasearch-client-specs/pull/31/files.

Here is an example on python: https://github.com/algolia/algoliasearch-client-python/pull/433/files.

**Goal**: make sure developers can set the event timestamp when sending events using send_event/send_events.

**Comment by tkrugg** [comment]
it's already the case, like proves this test: 
https://github.com/algolia/search-insights.js/blob/master/lib/__tests__/_sendEvent.test.ts#L287-L320

I'll close this for now but feel free to reopen if I misunderstood your point.
