### ISSUE TITLE
Avoid to override the reference of window.aa

### ISSUE THREAD

**Issue by samouss** [algolia/search-insights.js#127]
The current implementation overrides the reference of `window.aa`. It leads to issues once the reference is given to a function for example. We advocate for an implementation like this in [React InstantSearch](https://algolia.com/doc/api-reference/widgets/hits/react/#sending-click-and-conversion-events). 

The `connectHitInsights` captures the first reference but it gets replaces later once insights is fully loaded. When end-users call the `insights` function provided to the component it silently fail, which makes it particularly complicated to find. It fails because the `insights` function is calling the original reference of the function.

**Comment by Haroenv** [comment]
What do you see as the solution to not override it?

**Comment by tkrugg** [comment]
I'll try to fix this by the end of the week, it is indeed a very annoying bug. 
The quick workaround is for now to pass the insightsClient in the following way

```js
// replace this
connectHitInsights(window.aa)(Hit);

// by this
connectHitInsights((...args) => window.aa(...args))(Hit);
```
