### ISSUE TITLE
examples for React-instantSearch and Angular-instantSearch missing

### ISSUE THREAD

**Issue by kataweina** [algolia/search-insights.js#160]
Hello team,
It appears that the links to library examples offered in the documentation are missing (relocated to another repo or removed?).
could you please update the links or remove them from the docs.

Thank you, and happy coding!

**Comment by Haroenv** [comment]
The examples are now here @kataweina https://github.com/algolia/doc-code-samples

Could you tell me where the links should be changed so I can fix it? Thanks!

**Comment by tkrugg** [comment]
To complete @Haroenv's answer for anyone finding this issue:
- InstantSearch: [code](https://github.com/algolia/doc-code-samples/tree/master/InstantSearch.js/algolia-insights) | [view in codesandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/InstantSearch.js/algolia-insights)
- React InstantSearch: [code](https://github.com/algolia/doc-code-samples/tree/master/React%20InstantSearch/algolia-insights) | [view in codesandbox](https://github.com/algolia/doc-code-samples/tree/master/React%20InstantSearch/algolia-insights)
- Angular InstantSearch: [code](https://github.com/algolia/doc-code-samples/tree/master/Angular%20InstantSearch/algolia-insights) | [view in codesandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/Angular+InstantSearch/algolia-insights)
- Vue InstantSearch: [code](https://github.com/algolia/doc-code-samples/tree/master/Vue%20InstantSearch/algolia-insights) | [view in codesandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/Vue%20InstantSearch/algolia-insights)
