### ISSUE TITLE
Add wait on response

### ISSUE THREAD

**Issue by maxiloc** [algolia/search-insights.js#199]
I'd like to do the following in the browser:

```
const res = await aa.sendEvent(this.eventType, this.eventJson);
console.log(res);
```

For that to be possible I think we would need to both:
- allow to force the requester (xml)
- return a promise

**Comment by Haroenv** [comment]
Why do you want to force waiting for the response? This seems like bad practice e.g. on page navigation

**Comment by maxiloc** [comment]
This is not for navigation 😄. This is for testing

**Comment by Haroenv** [comment]
Interesting, could you not look at the network tab to see if the request worked?

**Comment by maxiloc** [comment]
You'll see in my upcoming email, but my goal is to avoid being a developer to play around with sending events 😄

**Comment by Haroenv** [comment]
To make this possible:

Add return here:

https://github.com/algolia/search-insights.js/blob/29678b2d2cafd5559887454a9ae623fe69201652/lib/_sendEvent.ts#L129

and here:

https://github.com/algolia/search-insights.js/blob/29678b2d2cafd5559887454a9ae623fe69201652/lib/_sendEvent.ts#L150

call constructor with custom requestFn:

https://github.com/algolia/search-insights.js/blob/e551d106464edbcc5304047d398a7b0df48c0823/lib/insights.ts#L115

Make custom requester which is like these, but with a promise (so e.g. fetch)

https://github.com/algolia/search-insights.js/blob/29678b2d2cafd5559887454a9ae623fe69201652/lib/utils/request.ts#L3-L6

Meaning the only two changes needed to make that work are returning the value of the requestFn, and in your case making sure it returns a promise.

What do you think?

**Comment by maxiloc** [comment]
yes if we can get the response from the sendBeacon method that would be great

**Comment by Haroenv** [comment]
Note that `sendBeacon` only returns a boolean (true or false), but simply returning the value isn't an issue I think, even though it used to return undefined. cc @tkrugg

**Comment by maxiloc** [comment]
ah yes I missed your about using the constructor with custom requestFn. With the two returns we should be good yes

**Comment by Haroenv** [comment]
Will release monday

**Comment by Haroenv** [comment]
1.4.0
