### ISSUE TITLE
Package deprecated?

### ISSUE THREAD

**Issue by Epenance** [algolia/search-insights.js#227]
Hi there,

I'm about to implement personalisation event on a larger solution and just noticed that the package was deprecated 5 days ago, https://www.npmjs.com/package/search-insights

Does this affect both the browser implementation from the CDN or just the npm install script?

And if so, what is the alternative to send events by?

**Comment by Haroenv** [comment]
Sorry, the deprecation was done by mistake and should be reverted. You can ignore it and implement with cdn or npm with this package!

**Comment by Epenance** [comment]
Alright, perfect! 😄  Thought it might be something like that.

**Comment by Haroenv** [comment]
The deprecation message has been removed 👍
