### ISSUE TITLE
insights.algolia.io returns 401 Unauthorized

### ISSUE THREAD

**Issue by cspeer** [algolia/search-insights.js#240]
Hi,

I just implemented Algolia's Insights like so:

```js
import algoliasearch from 'algoliasearch/lite';
import instantsearch from 'instantsearch.js';
import { someWidget } from 'instantsearch.js/es/widgets';
import { createInsightsMiddleware } from 'instantsearch.js/es/middlewares';
import aa from 'search-insights';

const insights = createInsightsMiddleware({
  insightsClient: aa
});

const search = instantsearch({
  indexName: 'IndexName',
  searchClient: algoliasearch('P0GDJ8T2IZ', '**********'),
});

search.use(insights);

search.addWidgets([
  configure({
    clickAnalytics: true,
  }),

  someWidget({}),
]);

search.start();
```

The Insight Validator Chrome extension says everything is fine and recognizes the search being performed.
However, upon taking a look into firefox's console, I can see that the request to `https://insights.algolia.io` failed with a 401 Unauthorized:
![algolia insights 401](https://user-images.githubusercontent.com/326824/103811206-dc68c880-505c-11eb-9303-b41d61636439.png)
You can see that app id and key are both sent along properly. Also both keys work perfectly fine with instantsearch.js.
What am I missing here? Did I fail to enable the feature somewhere or something like that?

Thanks,
Chris

**Comment by Haroenv** [comment]
I checked, and the plan on which you are doesn't support click analytics yet. In all newer plans click analytics is included, so if you want to change plan, your can support@algolia.com, or update from the dashboard itself.

I'll check with the documentation team if we can make this "availability" issue clearer somehow

**Comment by cspeer** [comment]
Well, that's a bummer.

However, we're not just trying to use click analytics. It's just the regular insights API that we wanted to employ, like which filters/facets are being used. Is that also not included?

**Comment by Haroenv** [comment]
Unfortunately that's under the same feature switch. Our new plans should however be cheaper for the same usage, so I'd advice you to take a look or contact your sales contact to see how we can help!

**Comment by cspeer** [comment]
Thanks @Haroenv 
I'm already in touch with sales. Turns out however, that it would more than double our monthly costs just to have this feature.

**Comment by Haroenv** [comment]
I'm sorry to hear that. In the mean time I think this issue should probably be closed. Hope you have a nice day otherwise!
