### ISSUE TITLE
Firefox warning on _ALGOLIA Cookie soon to be rejected

### ISSUE THREAD

**Issue by tkrugg** [algolia/search-insights.js#254]
![image](https://user-images.githubusercontent.com/2982512/114854018-acac2800-9de4-11eb-9704-a6509ae2eb2d.png)

To reproduce:
1. Open https://180jd.csb.app/ in firefox
2. Open the console, the warning should appear.

**Comment by Haroenv** [comment]
I'm wondering if cookies are even the right approach here. Wouldn't localStorage or similar be enough? I don't think you can set a sameSite cookie from js: https://stackoverflow.com/a/58816189/3185307

**Comment by Haroenv** [comment]
Alternatively we should get rid of it altogether (planned to make it non-default in v2) and only support non-generated user token?

**Comment by eunjae-lee** [comment]
Checking this again, I no longer see that warning in my Firefox 94.0.2 (64-bit). Did something change?

**Comment by Haroenv** [comment]
@eunjae-lee, the sandbox uses search-insights@latest, so would be updated with v2 without cookie now

**Comment by eunjae-lee** [comment]
Oh you're right. I'm seeing it again 🤦🏻‍♂️
