### ISSUE TITLE
unfriendly type error

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/search-insights.js#268]
The following code is followed by an unfriendly type error:

```js
aa("clickedObjectIDsAfterSearch", {
  userToken: "user-1",
  eventName: "your_event_name",
  index: "your_index_name",
  queryID: "queryID",
  objectIDs: ["objectID1", "objectID2"],
  positions: [17, 19]
});
```

<img width="546" alt="CleanShot 2021-05-18 at 17 02 30@2x" src="https://user-images.githubusercontent.com/499898/118675374-d947cb00-b7fa-11eb-8ba4-b1f6298eda43.png">

reproduction: https://codesandbox.io/s/insights-typing-issue-with-clickedobjectidsaftersearch-oopv8?file=/src/index.ts

It turns out when a method is overloaded, the TypeScript iterates over each overload and checks if the code matches it and shows the result. For [example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiBiBXAdgYwIxQLxQBQFsJgALAewBMAuKAIgDMUMaAaKMAQwCd38BnagN4AoKKKjIeEar2CcAlsgDmAbiEBfAJTYAfFABupOeVVDQkWAkYAmbHkIkK1etZZsuPflGFio7cuU4IXk8ZeSVVTR19Q2MhU3BoOCQ0WyTGTAAyC2TUKxNyCFQAGy5oVFJkGSgGNGo0tBMa1FwAcib0FtZvMWIIIqLSahaAd1JOIvIW9Q0gA),

<img width="463" alt="CleanShot 2021-05-18 at 17 00 04@2x" src="https://user-images.githubusercontent.com/499898/118675581-fed4d480-b7fa-11eb-9c6b-08c5d3fbbf51.png">

↑ For that code, we get this ↓

<img width="887" alt="CleanShot 2021-05-18 at 16 59 59@2x" src="https://user-images.githubusercontent.com/499898/118675615-05634c00-b7fb-11eb-8328-d64fd75d7abf.png">

In our case, apparently there are quite a lot of overloads and I think TS is only showing the result for the last overload. Not sure how to improve this yet.

**Comment by fernandopadang** [comment]
i get some issue like this, when i used event 'clickedObjectIDsAfterSearch'.
in documentation we need call event clickedObjectIDsAfterSearch like this
```
aa('clickedObjectIDsAfterSearch', {
  index: 'INDEX_NAME',
  eventName: 'Click item',
  queryID: getQueryID(),
  objectIDs: ['object1'],
  positions: [42],
});
```
but on types of click is not declare eventName.
![image](https://user-images.githubusercontent.com/25701054/119214068-16a7a380-baee-11eb-9c43-1c389dd746e7.png)
so when i use event clickedObjectIDsAfterSearch without attribute eventName i get error like this
![image](https://user-images.githubusercontent.com/25701054/119214138-a3526180-baee-11eb-90e5-d3b8fd6ead0e.png)
