### ISSUE TITLE
clickedObjectIDsAfterSearch is incorrectly typed

### ISSUE THREAD

**Issue by thecuriouspixel** [algolia/search-insights.js#271]
Hello,

The insights documentation and the rest api calls show that an eventName is needed in order to make a `clickedObjectIDsAfterSearch` call

```
aa('clickedObjectIDsAfterSearch', {
    userToken: string,
    index: string,
    eventName: string,
    queryID: string,
    objectIDs: array,
    positions: array
});
```

But this method is typed as:
`export declare function clickedObjectIDsAfterSearch(params: InsightsSearchClickEvent): void;`

and the type is:
```
export interface InsightsSearchClickEvent {
    userToken?: string;
    timestamp?: number;
    index: string;
    queryID: string;
    objectIDs: (string | number)[];
    positions: number[];
}
```

This fails linting if you try to add an `eventName`, and I believe it fails if used without an `eventName` as a malformed object.

We had to override locally starting from the insightClient to cleanly have this pass linting.

Thanks.

**Comment by eunjae-lee** [comment]
Hello @thecuriouspixel 
Yes it's indeed wrong. If you update it to 2.0.1, it will be fixed. Let us know how it goes :)
