### ISSUE TITLE
Write the examples including the build process or in a way without build process

### ISSUE THREAD

**Issue by Haroenv** [algolia/search-insights.js#3]
It's nice to be able to literally copy/paste examples, but that's not possible here, since they assume some build process to inject the scripts and do babel, but it's not included in the projects. 

Would be nice to have a setup more like [InstantSearch templates](https://github.com/algolia/instantsearch-templates), cc @vvo

**Comment by vvo** [comment]
Once this is released, we could definitely add those examples to InstantSearch templates

**Comment by vvo** [comment]
@Haroenv were you trying to debug/do a demo of the insights with InstantSearch.js? If so we could definitely add those examples in InstantSearch templates

**Comment by Haroenv** [comment]
I looked at the examples in the context of https://github.com/algolia/instantsearch.js/issues/2779

**Comment by vvo** [comment]
I think this is a different issue, the real fix for this InstantSearch.js issue is to update the Algolia documentation about click analytics which should not redirect to a GitHub readme on how to load the library.

Loading the library must be cleary explained in the current tutorial: https://www.algolia.com/doc/tutorials/getting-started/how-to-implement-analytics/#reporting-click-and-conversion-events

This is not the case today so users might just not do it. The less hops you need to do the better in term of achieving what you want following a documentation.

cc @codeharmonics what do you think?

**Comment by codeharmonics** [comment]
Hi Vincent,

I'll create an issue. Will adding the below snippet/explanation be sufficient? Or is there more that needs to be mentioned?

Peter
Getting started

 <https://github.com/algolia/search-insights.js/blob/master/README.md#loading-and-initializing-the-library> <>Loading and initializing the library

Insights library can be either loaded via jsDelivr CDN or directly bundled with your application. We recommend loading the library by adding the snippet below to all pages where you wish to track search analytics.

  <script>
    !function(e,a,t,n,s,i,c){e.AlgoliaAnalyticsObject=s,e.aa=e.aa||function(){(e.aa.queue=e.aa.queue||[]).push(arguments)},i=a.createElement(t),c=a.getElementsByTagName(t)[0],i.async=1,i.src="https://cdn.jsdelivr.net/npm/search-insights@0.0.14",c.parentNode.insertBefore(i,c)}(window,document,"script",0,"aa");

    // Initialize library
    aa('init', {
      applicationID: 'APPLICATION_ID',
      apiKey: 'SEARCH_API_KEY'
    })
  </script>
 <https://github.com/algolia/search-insights.js/blob/master/README.md#enabling-queryid-response-from-algolia-engine>

**Comment by vvo** [comment]
we can replace

> Insights library can be either loaded via jsDelivr CDN or directly bundled with your application. We recommend loading the library by adding the snippet below to all pages where you wish to track search analytics.

by

> To install the analytics library on your website, use this snippet:

No need for now to speak about npm

**Comment by tkrugg** [comment]
To answer the original, copy/paste examples are available, see: https://github.com/algolia/search-insights.js/issues/160#issuecomment-574585336
