### ISSUE TITLE
Is userToken type correct?

### ISSUE THREAD

**Issue by mackelito** [algolia/search-insights.js#324]
```
type SetUserToken = (method: "setUserToken", userToken: string | number) => void
```

Should it not also be possible to "unset" a userToken?
eg. for when a user logout?

`aa('setUserToken', undefined);`
gives
`Argument of type 'undefined' is not assignable to parameter of type 'string | number'.ts(2345)`

**Comment by mackelito** [comment]
> You can not send events without user token, so there's no point in removing the user token, it only makes sense to override the token

But the default is undefined and in that case a anonymous token will be set right?

**Comment by eunjae-lee** [comment]
If you use search-insights@v1, it creates an anonymous user token and stores it in cookie. You can get it 

```js
aa('getUserToken', null, (err, userToken) => {

});
```

and store it somewhere, and later re-use it.

**Comment by mackelito** [comment]
For sure but it's more likely to be the same user within the same session (rather unlikely not to be).
Still would like to know the importance of the anonymous data in such a case.. is it fine and will just be corrected in the mass of all things or do we need to take actions to cover it somehow? :)

**Comment by eunjae-lee** [comment]
To rephrase,

```js
const anonymousUserToken = createUUID();

aa('init', {
  // ...
  userToken: anonymousUserToken
});
```

when later logged in,

```js
aa('setUserToken', userIdFromDatabase);
```

when later logged out,

```js
aa('setUserToken', anonymousUserToken);
```

If you use cookie, then you can store this `anonymousUserToken`. Then it's slightly persistent compared to a random string in the memory. Then there's a chance this unlogged-in user next time with that anonymous user token get more personalized results from Algolia. However, this anonymous user token changes (clears browser cache, different browser, etc). So compared to persistent user token (that might come from your own database), it's not significant.

Does it answer your question? Let me know if you need any clarification :)
