### ISSUE TITLE
Should undefined be added as possible type?

### ISSUE THREAD

**Issue by mackelito** [algolia/search-insights.js#352]
based on discussions with Algoia I was told that if we passed in `undefied` to the `setUserToken` method  it would create a anonymous token.. but the type only allows for `string | number` 

https://github.com/algolia/search-insights.js/blob/79a1de478c3f712ed3d2a8270debefb20459fd8b/lib/_tokenUtils.ts#L45

Suggestion is to add `undefined` to the type

**Comment by mackelito** [comment]
@eunjae-lee a private chat with our contact person (not sure if it's ok to write names in here).
We have a SPA and when users login/out we update the userToken.

from what I can see the `setAnonymousUserToken()` is not available.

````
export declare type InsightsMethodMap = {
    init: Parameters<typeof init>;
    getVersion: Parameters<typeof getVersion>;
    addAlgoliaAgent: Parameters<typeof addAlgoliaAgent>;
    setUserToken: Parameters<typeof setUserToken>;
    getUserToken: Parameters<typeof getUserToken>;
    onUserTokenChange: Parameters<typeof onUserTokenChange>;
    clickedObjectIDsAfterSearch: Parameters<typeof clickedObjectIDsAfterSearch>;
    clickedObjectIDs: Parameters<typeof clickedObjectIDs>;
    clickedFilters: Parameters<typeof clickedFilters>;
    convertedObjectIDsAfterSearch: Parameters<typeof convertedObjectIDsAfterSearch>;
    convertedObjectIDs: Parameters<typeof convertedObjectIDs>;
    convertedFilters: Parameters<typeof convertedFilters>;
    viewedObjectIDs: Parameters<typeof viewedObjectIDs>;
    viewedFilters: Parameters<typeof viewedFilters>;
    sendEvents: Parameters<ReturnType<typeof makeSendEvents>>;
};
````

**Comment by eunjae-lee** [comment]
@mackelito I see. We do not expose `setAnonymousUserToken` to public. By the way, just to remind you, anonymous user token is stored in cookie (just in case you want to avoid cookie).

So this should be your flow:

```js
aa("init", { appId, apiKey, useCookie: true });  // it's true by default in search-insights@v1, and false by default in v2.
```

Right after `init`, an anonymous user token is set to the instance.

```js
let anonymousUserToken;
aa('getUserToken', null, (err, userToken) => {
  anonymousUserToken = userToken;
});
```

You can keep the token like that.

And when a user is logged in, then you can set more explicit user token:

```js
aa('setUserToken', userTokenLikeUserIdFromYourDatabase);
```

And when a user is logged out, you want to re-set anonymous user token:

```js
aa('setUserToken', anonymousUserToken);
```

Does it make sense to your flow? Let me know :)

**Comment by mackelito** [comment]
sure it makes sense.. although I would prefer it you exposed the internal method

**Comment by eunjae-lee** [comment]
> sure it makes sense.. although I would prefer it you exposed the internal method

Explicit user token is always better than anonymous one, so we do not _encourage_ it. Maybe we need a logic to fallback to previous anonymous user token when user token is cleared.

I'll close this issue for now, but don't hesitate to re-open for more discussion!
