### ISSUE TITLE
How to use this library in a React Native app?

### ISSUE THREAD

**Issue by MagicAce1988** [algolia/search-insights.js#355]
I am having a hard time finding examples on how to use this library in a React Native app? Are there any, anywhere?

**Comment by Fluf22** [comment]
Hey 👋🏻 

Sorry for coming back so late. If that can be of any help to you or anyone coming here later, here is our official doc: https://www.algolia.com/doc/guides/building-search-ui/going-further/native/react-hooks/

Then, you can just follow the search-insights.js setup here: https://www.algolia.com/doc/guides/building-search-ui/going-further/send-insights-events/react-hooks/

Please note that you may run into trouble with cookie handling if you setup your project with Expo, but our integration with bare React Native should work as expected!

I'll close this issue for now, but don't hesitate to re-open it if the docs aren't helpful!
Thanks 🙌🏻
