### ISSUE TITLE
Group typecheking in a function to lighten _sendEvent function

### ISSUE THREAD

**Issue by tkrugg** [algolia/search-insights.js#44]
follows up on this comment: https://github.com/algolia/search-insights.js/pull/34/files#r240540872

Problems to address:
- sendEvent function is a bit dense right now:
- do typecheking earlier. Typechecking is more useful when it happens at the start of a public method (click, conversion and view methods) rather then later.

**Comment by eunjae-lee** [comment]
closing the issue because the schema validations were removed https://github.com/algolia/search-insights.js/pull/325
