### ISSUE TITLE
Testing for localStorage breaks compatibility with older browsers

### ISSUE THREAD

**Issue by bazzanintelliact** [algolia/search-insights.js#556]
After upgrading to search-insights v2.16.3, we started seeing issues for users on older iOS and Android versions. 
This only seems to be the case if Cookies are disabled or when using Incognito/Private browsing. 

When trying to access localStorage following exception is thrown
`SecurityError: The operation is insecure.`

This is the line causing the issue:
https://github.com/algolia/search-insights.js/blob/d2c3e983c09854f5139cc31f0a1210b37829daa6/lib/utils/localStorage.ts#L5 

Wrapping the access to localStorage in a try/catch seems to fix the problem

**Comment by JasonBerry** [comment]
This issue is resolved in 2.17.2.

Thank you for reporting it!

**Comment by bazzanintelliact** [comment]
@JasonBerry Thank you for the quick fix!
