### ISSUE TITLE
Allow multiple clients to coexist

### ISSUE THREAD

**Issue by JonasBa** [algolia/search-insights.js#67]
We have a use case on the dashboard where we want to have multiple clients running, so we need a way to specify a window alias for each of those.

The feature is partially implemented via the last param of the load function `aa` which tells the script what window property to override => `(window,document,"script",0,"aa");`

The problem is that while the alias does work, the second time we try to override window.AlgoliaAnalyticsObject, that object no longer exists because it has already been overriden.

**Comment by tkrugg** [comment]
I guess something that could fix your problème is just exporting the `AlgoliaAnalytics` so that you can instantiate it yourself as many time as needed?
You will also need to customize the [init script](https://github.com/algolia/search-insights.js#loading-and-initializing-the-library) but that's easy.

**Comment by tkrugg** [comment]
this was addressed by updating the snippet in the docs.

```js
<script>
  var ALGOLIA_INSIGHTS_SRC = "//cdn.jsdelivr.net/npm/search-insights@1.3.1";

  !function(e,a,t,n,s,i,c){e.AlgoliaAnalyticsObject=s,e[s]=e[s]||function(){
  (e[s].queue=e[s].queue||[]).push(arguments)},i=a.createElement(t),c=a.getElementsByTagName(t)[0],
  i.async=1,i.src=n,c.parentNode.insertBefore(i,c)
  }(window,document,"script",ALGOLIA_INSIGHTS_SRC,"MY_CUSTOM_AA");

  aa('init', {
    appId: 'ZP039NUGT7',
    apiKey: '05df73a40f1c055808be2857410b22fc',
  });
</script>
