### ISSUE TITLE
[types] - expose types

### ISSUE THREAD

**Issue by JonasBa** [algolia/search-insights.js#9]
Right now we expose no interface nor types for the library. We already use them internally, but it would be great to expose them for the public functions.

**List of functions to type:**
- public init: (params: initParams) => void;
- public initSearch: (params: initSearchParams) => void;
- public click: (params?: Partial<ClickReport>) => void;
- public conversion: (params?: Partial<ConversionReport>) => void;
- public search: (params: SearchReport) => void;

**Comment by mrousavy** [comment]
2 Years later still no exposed types. How am I supposed to use this library on a backend server? Just guess the parameters?

**Comment by Haroenv** [comment]
You can use this library with JavaScript, or write a declaration file based on the types in the repository itself @mrousavy. Alternatively we'd also accept a PR gladly which exposes the types directly, we have just prioritised this, since nobody upvoted this issue in two years, hope you understand!

**Comment by abdelinho24** [comment]
Hi, 
Would be nice to prioritize this as it would be helpful for external React projects. 
Thanks.
